# Generated by Django 4.0.1 on 2022-02-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='permanent',
        ),
        migrations.AddField(
            model_name='spotreservation',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spotreservation',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
