# Generated by Django 4.0.1 on 2022-03-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotreservation',
            name='frequency',
        ),
    ]
