# Generated by Django 4.0.3 on 2022-03-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotreservation',
            name='permanent',
        ),
        migrations.AddField(
            model_name='spotreservation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked_for_user', 'Booked by user'), ('booked_for_team', 'Booked by team'), ('booked_permanently', 'Booked permanently')], default='available', max_length=20),
        ),
    ]
