# Generated by Django 4.0.1 on 2022-03-04 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_permanent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotreservation',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_for_spot', to='reservations.reservation'),
            preserve_default=False,
        ),
    ]
