# Generated by Django 4.0.3 on 2022-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_spotreservation_permanent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotreservation',
            name='status',
        ),
        migrations.AddField(
            model_name='spotreservation',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
