# Generated by Django 4.0.1 on 2022-03-14 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_remove_spotreservation_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotreservation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_spot_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
