# Generated by Django 4.0.1 on 2022-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_spotreservation_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotreservation',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
