# Generated by Django 4.0.3 on 2022-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_remove_room_capacity'),
        ('reservations', '0004_alter_spotreservation_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotreservation',
            name='spot',
        ),
        migrations.AddField(
            model_name='spotreservation',
            name='spots',
            field=models.ManyToManyField(to='workspaces.spot'),
        ),
    ]
