# Generated by Django 4.0.3 on 2022-03-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_spots_spotreservation_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotreservation',
            old_name='spot',
            new_name='spots',
        ),
    ]
