# Generated by Django 4.0.3 on 2022-03-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_rename_spot_spotreservation_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotreservation',
            name='permanent_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('allowed', 'Allowed'), ('declined', 'Declined')], default='submitted', max_length=20),
        ),
    ]
