# Generated by Django 4.0.3 on 2022-03-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_spotreservation_permanent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_by',
        ),
    ]
