version: '3.3'

volumes:
  postgres_data: { }

services:
  backend:
    image: "ghcr.io/dominikbullo/sharedesk_backend:${IMAGE_VERSION}"
    depends_on:
      - postgres
    restart: on-failure
    env_file: .env

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data # persist data even if container shuts down
    expose:
      - ${DB_PORT} # Publishes port to other containers but NOT to host machine
    command: -p ${DB_PORT}
    env_file: .env

  nginx:
    image: "ghcr.io/dominikbullo/sharedesk_nginx:${IMAGE_VERSION}"
    depends_on:
      - backend
    env_file: .env
    expose:
      - 80
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}


  backups:
    image: prodrigestivill/postgres-backup-local
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - /tmp/backups/:/backups/

