version: "3"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env.ci

  # postgres database
  postgres:
    image: postgres
    expose:
      - ${DB_PORT} # Publishes port to other containers but NOT to host machine
    command: -p ${DB_PORT}
    env_file: .env.ci
