# Generated by Django 4.0.1 on 2022-03-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_options_rename_title_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
    ]
