# Generated by Django 4.0.1 on 2022-03-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=10),
        ),
    ]
