# Generated by Django 4.0.1 on 2022-03-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_members'),
        ('users', '0002_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, to='teams.Team'),
        ),
    ]
