# Generated by Django 4.0.1 on 2022-02-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_spotissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotissue',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
