# Generated by Django 4.0.1 on 2022-03-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_layout_created_by_alter_room_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='spotissue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='created_by',
        ),
    ]
