# Generated by Django 4.0.3 on 2022-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_room_columns_room_rows_spot_column_spot_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rows',
        ),
        migrations.AddField(
            model_name='roomlayout',
            name='columns',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomlayout',
            name='rows',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
