# Generated by Django 4.0.3 on 2022-03-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_remove_layout_created_by_remove_room_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotissue',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.spot'),
        ),
    ]
