# Generated by Django 4.0.3 on 2022-03-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_alter_spot_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='floor_number',
            new_name='number',
        ),
    ]
