# Generated by Django 4.0.3 on 2022-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_rename_floor_number_floor_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='name',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='spotissue',
            name='subject',
            field=models.CharField(default='Default issue', max_length=255),
            preserve_default=False,
        ),
    ]
