# Generated by Django 4.0.3 on 2022-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_rename_name_spot_identifier_spotissue_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotissue',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='submitted', max_length=20),
        ),
    ]
