# Generated by Django 4.0.3 on 2022-03-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_spot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='status',
        ),
    ]
