# Generated by Django 4.0.3 on 2022-03-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_alter_room_name_alter_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
