# Generated by Django 4.0.3 on 2022-03-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_remove_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='identifier',
            field=models.CharField(default='default identifier', max_length=255),
            preserve_default=False,
        ),
    ]
