name: Deploy to production server

on:
  workflow_run:
    workflows: [ "Build & Publish to registry" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare production server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_DIR }} &&\
            git fetch --all &&\
            git reset --hard origin/master  &&\
            git pull origin master &&\
            echo "${{ secrets.SHAREDESK_GITHUB_PACKAGE_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin &&\
            cp docker-compose.prod.yml docker-compose.override.yml


      - name: Pull & recreate containers on production server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_DIR }} &&\
            docker-compose -f docker-compose.prod.yml pull &&\
            docker-compose -f docker-compose.prod.yml up -d --build backend --force-recreate &&\
            docker-compose -f docker-compose.prod.yml up -d --build nginx --force-recreate
