name: Deploy to staging server

on:
  workflow_run:
    workflows: [ "Build & Publish to registry" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to staging server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ${{ secrets.PROJECT_DIR }} &&\
            git pull origin master &&\
            echo "${{ secrets.SHAREDESK_GITHUB_PACKAGE_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin &&\
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull &&\
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml build &&\
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml down &&\
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
